# DON'T USE TABS!!!

# Site settings
title: CEC | Composer
email: christopher.e.chandler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Website for the composer Christopher Chandler.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
gems: [jekyll-paginate]
paginate_path: "/home/page:num"

# Build settings
markdown: kramdown

# Navigation
navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about/
 - title: Music
   url: /music/
 - title: Recordings
   url: /recordings/
 - title: Performances
   url: /performances/

# Outputting
permalink: /:year/:month/:day/:title
paginate: 10
